//
//  ContentView.swift
//  JumpySwiftUITextView
//
//  Created by Joseph Cheung on 1/2/2023.
//

import SwiftUI

struct ContentView: View {
    @State var activeTab = 1

    var body: some View {
        TabView(selection: $activeTab) {
            TextKit1View(activeTab: $activeTab)
                .tabItem {
                    Label("TextKit1 Scroll", systemImage: "list.dash")
                }
                .tag(1)
            
            TextKit2View(activeTab: $activeTab)
                .tabItem {
                    Label("TextKit2 Scroll", systemImage: "list.dash")
                }
                .tag(2)
            
            TextKit2AdjustView()
                .tabItem {
                    Label("TextKit2 Adjust", systemImage: "list.dash")
                }
                .tag(3)
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

let sampleContent = """
    Choosing the Right Extension Approach Choosing the Right Extension Approach Choosing the Right Extension Approach Choosing the Right Extension Approach

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.

    We’ve looked at the built-in text controls, the components in the TextKit stack, and how to configure those components to achieve different effects.  There’s a lot you can do with that knowledge already, but if you need even more, you’ll need to extend parts of TextKit.  So now we’ll talk a little bit about choosing the right approach for that.  And choosing the right approach is like building up your text toolbox.  It’s like going to the hardware store because you need a hammer, and then when you get there, there’s this giant wall of hammers to choose from.  You want to pick the hammer that can do the job, and the least expensive one that will do what you need.  So these are the hammers that are available to us.  Delegation is like your standard hammer with the claw on the end, it’s useful for multiple tasks.  The delegates have a lot of commonly desired customization hooks and most of the time it’ll get the job done.  Notifications is like a ball-peen hammer, which has a ball on the end instead of a claw.  It’s more specialized and better suited for certain tasks than the standard hammer of delegation, but it’s not quite as versatile.  And finally, subclassing is your sledgehammer.  You can use the sledgehammer for just about anything you’d need a hammer for, but it’s probably overkill for a lot of things.
"""
